
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Feature-Policy = "accelerometer 'none'; ambient-light-sensor 'none'; magnetometer 'none'; usb 'none'"
    Referrer-Policy = "same-origin"
    Expect-CT = "max-age=864000; enforce"
    X-DNS-Prefetch-Control = "on"
    X-UA-Compatible = "ie=edge"

